version: "3.7"

networks:
  coin:
    driver: bridge
    ipam:
      config:
        - subnet: 173.0.0.0/24

services:
  coin:
    image: coin
    container_name: coin
    build:
      context: ..
      dockerfile: dockerfiles/coin.Dockerfile
    command: sh -c "poetry run python run.py"
    restart: unless-stopped
    env_file: ../secrets/coin.env
    tty: true
    networks:
      - coin
