version: "3.7"

networks:
  coin:
    driver: bridge
    ipam:
      config:
        - subnet: 173.0.0.0/24

services:
  db:
    image: postgres:13-alpine
    container_name: coin_db
    restart: unless-stopped
    env_file: ../secrets/db.env
    tty: true
    volumes:
      - ../data:/var/lib/postgresql/data
    networks:
      - coin

  coin:
    image: coin
    container_name: coin
    build:
      context: ..
      dockerfile: dockerfiles/coin.Dockerfile
    command: sh -c "poetry run python run.py"
    restart: unless-stopped
    env_file: ../secrets/coin.env
    tty: true
    networks:
      - coin
    depends_on:
      - db
